In [2]:
import pandas as pd

df_flights = pd.read_csv('data/flights.csv')
df_flights

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,DestAirportName,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
0,2013,9,16,1,DL,15304,Tampa International,Tampa,FL,12478,John F. Kennedy International,New York,NY,1539,4,0.0,1824,13,0,0
1,2013,9,23,1,WN,14122,Pittsburgh International,Pittsburgh,PA,13232,Chicago Midway International,Chicago,IL,710,3,0.0,740,22,1,0
2,2013,9,7,6,AS,14747,Seattle/Tacoma International,Seattle,WA,11278,Ronald Reagan Washington National,Washington,DC,810,-3,0.0,1614,-7,0,0
3,2013,7,22,1,OO,13930,Chicago O'Hare International,Chicago,IL,11042,Cleveland-Hopkins International,Cleveland,OH,804,35,1.0,1027,33,1,0
4,2013,5,16,4,DL,13931,Norfolk International,Norfolk,VA,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,545,-1,0.0,728,-9,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271935,2013,9,20,5,VX,13204,Orlando International,Orlando,FL,12892,Los Angeles International,Los Angeles,CA,1730,1,0.0,1945,18,1,0
271936,2013,4,19,5,FL,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,11697,Fort Lauderdale-Hollywood International,Fort Lauderdale,FL,1020,24,1.0,1218,61,1,0
271937,2013,10,26,6,WN,12191,William P Hobby,Houston,TX,10821,Baltimore/Washington International Thurgood Ma...,Baltimore,MD,1540,30,1.0,1935,15,1,0
271938,2013,5,7,2,HA,13830,Kahului Airport,Kahului,HI,12173,Honolulu International,Honolulu,HI,609,-5,0.0,641,-6,0,0
271939,2013,6,11,2,UA,14771,San Francisco International,San Francisco,CA,14100,Philadelphia International,Philadelphia,PA,1338,60,1.0,2200,40,1,0

### Deal with null values

In [3]:
df_flights.isnull().sum()

df_flights[df_flights.isnull().any(axis=1)]

df_flights.DepDel15 = df_flights.DepDel15.fillna(0.0)   # sostituisco i valori nulli con 0.0

In [4]:
df_flights.isnull().sum()     # controllo se ci sono ancora valori nulli

Year                 0
Month                0
DayofMonth           0
DayOfWeek            0
Carrier              0
OriginAirportID      0
OriginAirportName    0
OriginCity           0
OriginState          0
DestAirportID        0
DestAirportName      0
DestCity             0
DestState            0
CRSDepTime           0
DepDelay             0
DepDel15             0
CRSArrTime           0
ArrDelay             0
ArrDel15             0
Cancelled            0
dtype: int64

### Deal with outliers

In [40]:
# Find mean, median, mode, maximum and minimum for DepDelay and ArrDelay columns

dep_mean = df_flights.DepDelay.mean()
dep_median = df_flights.DepDelay.median()
dep_mode = df_flights.DepDelay.mode()
dep_max = df_flights.DepDelay.max()
dep_min = df_flights.DepDelay.min()

arr_mean = df_flights.ArrDelay.mean()
arr_median = df_flights.ArrDelay.median()
arr_mode = df_flights.ArrDelay.mode()
arr_max = df_flights.ArrDelay.max()
arr_min = df_flights.ArrDelay.min()

print('Departures data:')
print(dep_mean)
print(dep_median)
print(dep_mode)
print(dep_max)
print(dep_min)

print('\nArrivals data:')
print(arr_mean)
print(arr_median)
print(arr_mode)
print(arr_max)
print(arr_min)

Departures data:
10.350448628373906
-1.0
0   -3
Name: DepDelay, dtype: int64
1425
-63

Arrivals data:
6.496649996322718
-3.0
0    0
Name: ArrDelay, dtype: int64
1440
-75

In [43]:
# plot distribuzione
import matplotlib.pyplot as plt

def show_distribution (col):
    delay_mean = col.mean()
    delay_median = col.median()
    delay_mode = col.mode()
    delay_max = col.max()
    delay_min = col.min()
    print(col.name,'\nMin:{}\nMax:{}\nMean:{}\nMedian:{}\nMode:{}'.format(delay_min, delay_max, delay_mean, delay_median, delay_mode))

    fig,ax = plt.subplots(1, 2, figsize=(12,6))

    ax[0].hist(col)
    ax[0].set_ylabel('Frequenza')

    ax[1].axvline(x = delay_min, color='grey', linestyle='dashed', Linewidth=2)
    ax[1].axvline(x = delay_max, color='green', linestyle='dashed', Linewidth=2)
    ax[1].axvline(x = delay_mean, color='red', linestyle='dashed', Linewidth=2)
    ax[1].axvline(x = delay_median, color='blue', linestyle='dashed', Linewidth=2)
    ax[1].axvline(x = delay_mode, color='yellow', linestyle='dashed', Linewidth=2)

# DA AGGIORNARE CON LA VERSIONE DI GITHUB